FROM golang:1.13.5-buster AS build

RUN mkdir -p /app/bin
RUN mkdir -p /app/manifests

WORKDIR /app

COPY ./service/ /app/

RUN go mod vendor

RUN go build -i -v -o /app/bin/ /app/server

VOLUME /app

# prod
FROM golang:1.13.5-buster

ARG BUNDLE_DIR

# This is a template Dockerfile for the bundle's invocation image
# You can customize it to use different base images, install tools and copy configuration files.
#
# Porter will use it as a template and append lines to it for the mixins
# and to set the CMD appropriately for the CNAB specification.

# You can control where the mixin's Dockerfile lines are inserted into this file by moving "# PORTER_MIXINS" line
# another location in this file. If you remove that line, the mixins generated content is appended to this file.
# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY --from=build /app/manifests $BUNDLE_DIR/service/manifests
COPY --from=build /app/bin $BUNDLE_DIR/service/bin