---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cnab-grpc-service
    labels:
        app: cnab-grpc-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: cnab-grpc-service
    template:
        metadata:
            labels:
                app: cnab-grpc-service
        spec:
            containers:
            - name: api
              image: localhost:5000/porter-sample-grpc-service:latest
              imagePullPolicy: Always
            #   command: ["/bin/sh", "-c", "/cnab/app/service/bin/server"]
              command: ["/bin/sh"]
              args:
                - "-c"
                - "/cnab/app/service/bin/server"
              ports:
                - containerPort: 50051
